# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.6352987  0.74899563 0.07065087]
  [0.22118452 0.70745671 0.01835809]
  [0.09074982 0.96032243 0.55478776]]

 [[0.7597166  0.21858422 0.65986474]
  [0.39772533 0.39713099 0.69955096]
  [0.50745623 0.50132865 0.62944093]]

 [[0.98064725 0.89446795 0.26670978]
  [0.90048248 0.31726032 0.98807543]
  [0.10165939 0.36684316 0.51787273]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.95895023 0.2479628  0.03432734 0.65122458 0.49311107]
 [0.82216423 0.2142706  0.20166854 0.01610121 0.76916089]
 [0.16280494 0.17670575 0.70174409 0.64356733 0.65653367]
 [0.53836609 0.9542699  0.58752366 0.36556115 0.42212709]
 [0.61914929 0.09225005 0.66774698 0.07308833 0.68678416]]
After normalization:
[[1.         0.24591592 0.01933091 0.67362149 0.5059239 ]
 [0.85492268 0.21018147 0.19681553 0.         0.79870654]
 [0.1555962  0.17033961 0.72720325 0.6655001  0.6792524 ]
 [0.55392207 0.99503597 0.60605934 0.37064252 0.43063722]
 [0.63960196 0.08076462 0.6911454  0.0604414  0.71133652]]


# 5.  How to find common values between two arrays?

In [7]:
import numpy as np
array1 = np.array([0, 1, 2, 4, 6])
print("Array 1: ",array1)
array2 = np.array([1, 3, 4])
print("Array 2: ",array2)
print("Common values between the arrays:")
print(np.intersect1d(array1, array2))
np.set_printoptions(threshold=np.inf)

Array 1:  [0 1 2 4 6]
Array 2:  [1 3 4]
Common values between the arrays:
[1 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [10]:
A = np.array([[1,2],[7,6]])
B = np.array([[1,2],[3,6]])
comparison = A == B
equal_arrays = comparison.all()
print(equal_arrays)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
from numpy import array
print("Random vector of size 10:")
v = np.random.randint(1,20, size = 10)
print(v)
v[v.argmax()] = 0
print("\nReplacing the maximum value by 0:")
print(v)

Random vector of size 10:
[19 18 14  9  3 18  7  2 13 13]

Replacing the maximum value by 0:
[ 0 18 14  9  3 18  7  2 13 13]


# 9. How to print all the values of an array?

In [12]:
x = np.arange(101)
np.set_printoptions(threshold=np.inf)
print(x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


# 10.Subtract the mean of each row of a matrix

In [13]:
import numpy as np
print("Original matrix:\n")
a = np.arange(12).reshape(3,4)
print(a)
print("\nSubtract the mean of each row of the matrix:\n")
b = a - a.mean(axis=1, keepdims = True)
print(b)

Original matrix:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Subtract the mean of each row of the matrix:

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [15]:
#given vector
a = np.random.randint(1,8,8)
print("Given vector:", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [2 1 1 6 6 3 3 1]
Indexing vector: [0 0 0 0 0 1 1 3]
Result: [3 2 1 7 6 3 3 1]


# 12.How to get the diagonal of a dot product?

In [16]:
X = [[1,2],[3,4]]
Y = [[1,2],[3,4]]
Z = np.diag(np.dot(X,Y))
Z

array([ 7, 22])

# 13.How to find the most frequent value in an array?

In [17]:
import numpy as np
x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 1 6 0 4 0 4 8 3 8 9 6 8 0 7 6 0 3 8 4]
Most frequent value in the above array:
0


# 14.How to get the n largest values of an array

In [18]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print("Largest value of the array is",x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
Largest value of the array is [9]


# 15.How to create a record array from a regular array?

In [19]:
import numpy as np
a1=np.array(['Ferrari','Mercedes','McLaren','Red Bull'])
a2=np.array(['Red','Grey','Orange','Blue'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])

('Ferrari', 'Red')
('Mercedes', 'Grey')
('McLaren', 'Orange')
